// <auto-generated />
using System;
using FCG.Infrastructure.Identidade.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FCG.Infrastructure.Identidade.Persistence.Migrations
{
    [DbContext(typeof(IdentidadeDbContext))]
    [Migration("20260119195437_MigrationInitialIdentidade")]
    partial class MigrationInitialIdentidade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identidade")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FCG.Domain.Identidade.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("ExpiracaoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiracao_em");

                    b.Property<int?>("MotivoRevogacao")
                        .HasColumnType("integer")
                        .HasColumnName("motivo_revogacao");

                    b.Property<bool>("Revogado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("revogado");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<Guid?>("SubstituidoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("substituido_por_id");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("SubstituidoPorId")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", "identidade");
                });

            modelBuilder.Entity("FCG.Domain.Identidade.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.HasKey("Id");

                    b.ToTable("usuarios", "identidade");
                });

            modelBuilder.Entity("FCG.Domain.Identidade.Entities.RefreshToken", b =>
                {
                    b.HasOne("FCG.Domain.Identidade.Entities.RefreshToken", "SubstituidoPor")
                        .WithOne()
                        .HasForeignKey("FCG.Domain.Identidade.Entities.RefreshToken", "SubstituidoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FCG.Domain.Identidade.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubstituidoPor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FCG.Domain.Identidade.Entities.Usuario", b =>
                {
                    b.OwnsOne("FCG.Domain.Identidade.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Valor")
                                .IsUnique()
                                .HasDatabaseName("ix_usuarios_email");

                            b1.ToTable("usuarios", "identidade");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("FCG.Domain.Identidade.ValueObjects.SenhaHash", "SenhaHash", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Senha")
                                .IsRequired()
                                .HasColumnType("char(69)")
                                .HasColumnName("senha");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("usuarios", "identidade");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("SenhaHash")
                        .IsRequired();
                });

            modelBuilder.Entity("FCG.Domain.Identidade.Entities.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
